### ISSUE TITLE
What happens now?

### ISSUE THREAD

**Issue by jlengstorf** [gatsbyjs/peril-gatsbyjs#27]
Is this thing on?

**Comment by SD10** [comment]
@jlengstorf It just doesn't make sense that this is not working. The setup is identical to Moya's.
I have to ask again because this could be a case of not have the appliance plugged in.

Are these permissions properly set on the Gatsby peril app on GitHub?

We have to subscribe to issue events
![screen shot 2018-08-15 at 8 59 38 pm](https://user-images.githubusercontent.com/7445580/44182873-5b48b980-a0ce-11e8-8009-e08680f67c02.png)

Peril needs read & write access to issues
![screen shot 2018-08-15 at 8 59 49 pm](https://user-images.githubusercontent.com/7445580/44182874-5d127d00-a0ce-11e8-804e-ee933d844428.png)

**Comment by SD10** [comment]
Oh sorry, I seemed to have already asked you this question last week 😢

**Comment by jlengstorf** [comment]
This is what I've got:

<img width="842" alt="screen shot 2018-08-16 at 8 25 41 am" src="https://user-images.githubusercontent.com/163561/44218223-1a808d00-a12e-11e8-9355-38cf79813a00.png">
<img width="838" alt="screen shot 2018-08-16 at 8 25 57 am" src="https://user-images.githubusercontent.com/163561/44218230-1d7b7d80-a12e-11e8-928c-a849fe68d215.png">

As far as I can tell, this is all correct.

**Comment by SD10** [comment]
Yeah it is 😞 Frustrating

**Comment by jlengstorf** [comment]
@SD10 I just gave you access to this repo and Heroku if you'd like to poke around. I've also got https://github.com/danger/peril/issues/351 open to clarify some things. It looks like something upstream may have changed, but I'm not really clear on what it is.
